### ISSUE TITLE
Contact page: wrong mailing list

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/frontend#11]
On https://yangcatalog.org/contact.html, the "YANG catalog announce mailing list" should point to: https://www.ietf.org/mailman/listinfo/yc-announce

@xorrkaz @mcr

**Comment by richardzilincikPantheon** [comment]
Thanks, resolved with [this commit](https://github.com/YangCatalog/frontend/commit/34dac30a7df3bea6d4bb9451f8091a85d4ad4f8c). The change will be visible on the page after our release next week.
