### ISSUE TITLE
Search on the full module name does not return it

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/frontend#12]
[Unsure whether I post this issue in the right repo, feel free to report elsewhere]

When searching for `ietf-voucher` on the main search page https://yangcatalog.org/yang-search using the advanced search with maturity-level = ratified, it returns 13 results about 'ietf-voucher-request' but none of 'ietf-voucher' alone (which exists).

Did some explorations and it may be related to a cache somewhere

**Comment by richardzilincikPantheon** [comment]
This is due to it being filtered out by the "Only Latest Revs" option in the "Search Options" tab. There is an older revision of `ietf-voucher`, `2018-05-09`, that was published in an RFC. The latest version, `2021-07-04`, has only appeared in a draft, so it's maturity is set to "adopted".

**Comment by richardzilincikPantheon** [comment]
I'll close this since it doesn't seem to be a bug. Feel free to reopen if I didn't answer your question.
