### ISSUE TITLE
Add a 'ratified' check-box on the main search page

### ISSUE THREAD

**Issue by evyncke** [YangCatalog/frontend#13]
As it appears that some users' (like @mcr) intention is to search only for ratified modules, a check-box 'Ratified' (default off/false) should appear in the main search page (next to 'only latest revs') and of course the search itself should take this setting into account.

@bclaise

**Comment by rjsparks** [comment]
is `ratified` a concept that's defined somewhere? Is it the best word to use on the UI?

**Comment by mcr** [comment]
> is `ratified` a concept that's defined somewhere? Is it the best word to use on the UI?

It's not exactly the word I would have picked, but it actually works for me.
I just wanted the default to be to be search RFCs only.  If there were further results, one could highlight that.   
Saying, "Standards Action" might be more correct, and you could refer to 8126, but I dunno.

**Comment by evyncke** [comment]
Or should we say "Include drafts" and of course reversing the meaning with a default being checked/true ?

**Comment by SlavomirMazurPantheon** [comment]
Hello all,

thank you for your input - so what you agreed on is:
- **UI:** new checkbox with a label `Include drafts` that will be un-checked by default.
- **Search engine:** Return only the results from the RFCs unless `Include drafts` is checked by user - then return also from drafts.

![image](https://user-images.githubusercontent.com/67378888/208379447-4565b4e3-7d64-4143-9995-edce48c9ffdd.png)

Regards,
Slavomír Mazúr

**Comment by evyncke** [comment]
@SlavomirMazurPantheon you are correct *EXCEPT* that the default should be 'include drafts'

**Comment by SlavomirMazurPantheon** [comment]
Okay, thank you @evyncke

**Comment by richardzilincikPantheon** [comment]
@SlavomirMazurPantheon @evyncke
I think having a 'ratified' checkbox as originally suggested would make more sense. Modules published by organizations other than the IETF are neither ratified, nor would they be published in drafts.
