### ISSUE TITLE
Reconsider `ratified`

### ISSUE THREAD

**Issue by rjsparks** [YangCatalog/frontend#17]
I am very concerned that `ratified` is a dangerous word to use, even in the code, but especially in anything that an end user might see (including casual end users that might look at github issues).

What alternatives were considered? Why wasn't `approved` sufficient?

**Comment by xorrkaz** [comment]
Why are you concerned over ratified?  I chose this word as yc.o incorporated other SDOs that had different, well, ratified states.  Approved didn't ring right as a WG adopts a document and that is a form of approval.  I wanted a word that conveyed ultimate consensus from the governing body.

**Comment by evyncke** [comment]
I tend to agree with @xorrkaz to be consistent among SDO

**Comment by xorrkaz** [comment]
As I read my comment it might come across defensive.  Not my intent.  Genuinely curious.  And if there is a better word, I'm all for it.

**Comment by evyncke** [comment]
The point is about isse #13 so search only on published documents and not drafts. I have suggested to revert the meaning to use 'draft' rather than [ratified|published|standard]

**Comment by rjsparks** [comment]
Consistent among SDOs includes consistent with IETF, and this is an IETF supported project, and IETF is the principal user.

`ratified` has no meaning in the IETF. I really think using this term _will_ cause confusion in the IETF process later on. (Though it didn't bother @mcr when this was discussed at #13).

I am surprised that `approved` also triggered confusion worry for @xorrkaz, but will take that as a strong indication that _that particular_ word isn't going to work both inside and outside the community.

Will Éric's suggestion of reversing the sense work better?

Sorry if this looks like a bike-shed argument, but naming is hard, and adding a word to the vocabulary about the status of IETF documents makes me very uncomfortable.

**Comment by xorrkaz** [comment]
Totally agree that naming is hard.  I settled on "ratified" way back before this was more official IETF software.  I like Éric's suggestion.

**Comment by mcr** [comment]
> Consistent among SDOs includes consistent with IETF, and this is an IETF supported project, and IETF is the principal user.
> 
> `ratified` has no meaning in the IETF. I really think using this term _will_ cause confusion in the IETF process later on. (Though it didn't bother @mcr when this was discussed at #13).

While `ratified` doesn't mean anything at the IETF, I think that most IETFers would understand it.
I am not attached in anyway to that word though.  `approved` is okay, but as Erick suggests, we could also go the opposite direction and say, `draft` or `work-in-progress` or even `not approved`... 

What I think is that when someone does a search (particularly, when a search engine visits, which maybe we don't want), that they should not get a confusion of work-in-progress YANG modules by default unless they specifically ask for that.
I know what it's all about, and I found it really difficult to find the approved/ratified YANG module that I wanted.

If the result set for "not draft" is empty, then by all means, give the user a note, "There are WIP documents that match"

**Comment by bclaise** [comment]
Yes, naming is hard, especially with cross-SDOs project.
I recall the "ratified" was discussed with the BBF people at the time (and IEEE if not mistaken)

Regards, Benoit

**Comment by SlavomirMazurPantheon** [comment]
In the communication for Release notes v5.9.0, we did not agree on the change, so we leave it with the label `Include Drafts`.
In case you will find out better naming please open new Github issue - I am closing this one now.
