### ISSUE TITLE
`[object Object]` displayed instead of revisions

### ISSUE THREAD

**Issue by richardzilincikPantheon** [YangCatalog/frontend#31]
![image](https://user-images.githubusercontent.com/85497288/224266084-23b86ad2-a1a8-4104-9451-f9c4b04e2a94.png)

The issue carries over when a different module is searched, however it goes away after refreshing the page. After this has been done, the issue is also fixed when a different module is searched.
The issue comes back when I visit https://yangcatalog.org/yang-search/module_details again.

**Comment by dmytro-kyrychenko** [comment]
Seems like it is no longer reproducible, so we can close it for now
