### ISSUE TITLE
IMPACT ANALYSIS: Throwing 500 Server error

### ISSUE THREAD

**Issue by xorrkaz** [YangCatalog/frontend#38]
Benoit Claise is reporting that this URL https://yangcatalog.org/yang-search/impact_analysis/ietf-interfaces@2018-02-20 is throwing an error, "The application has encountered an unknown error."  I can reproduce this as well.  It happens all the time.  See below for the error.

![image](https://github.com/YangCatalog/frontend/assets/9667809/0472e4b0-8594-4c3d-b344-075632a56b27)

**Comment by dmytro-kyrychenko** [comment]
Hi, Joe
Have you encountered this error with other modules?
I will look into it

**Comment by xorrkaz** [comment]
On 9/18/23 04:40, Dmytro Kyrychenko Pantheon wrote:
> Hi, Joe
> Have you encountered this error with other modules?

This was the only module Benoit mentioned.  I did not test others.

Joe

> I will look into it
>

**Comment by dmytro-kyrychenko** [comment]
Hello, just letting you know that we've found the source of the issue and working on the fix

**Comment by xorrkaz** [comment]
Excellent!  What was it?

**Comment by dmytro-kyrychenko** [comment]
Basically, the problem was not with this module, but with "if-l3-vlan@2015-10-19" and it is on pyang's side. So the server should have showed as a warning that this module was missing and the page for impact analysis would still load. We already have such error handling in that code, but this time it didn't work, so we need to fix it.

**Comment by xorrkaz** [comment]
Thanks.  What is the ETA on the fix so I can let Benoit know?

**Comment by dmytro-kyrychenko** [comment]
Well, we planned to do a release on the next week, so I hope this fix will make it in there

**Comment by dmytro-kyrychenko** [comment]
https://github.com/YangCatalog/backend/pull/802

**Comment by dmytro-kyrychenko** [comment]
https://github.com/YangCatalog/backend/pull/807
