### ISSUE TITLE
Not very clear how to open an issue

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/frontend#40]
All we see is at the bottom of the page "YANG Catalog: Established by [Cisco](https://www.cisco.com/), currently funded by the [IETF](https://www.ietf.org/), powered by many individual's code contributions [YANG Catalog.](https://github.com/YangCatalog/)"

NEW: YANG Catalog: Established by [Cisco](https://www.cisco.com/), currently funded by the [IETF](https://www.ietf.org/), powered by many individual's code contributions. Open issues at [YANG Catalog.](https://github.com/YangCatalog/)

**Comment by dmytro-kyrychenko** [comment]
Could you please clarify, do we need to edit this text at the bottom of every page?
![image](https://github.com/YangCatalog/frontend/assets/112940673/e310dcd5-3054-45f8-8e93-0887bb969537)

**Comment by bclaise** [comment]
Yes.
